version: "3.9"

services:
  ivy:
    container_name: Ivy
    build: ./ivy
    ports:
      - "${IVY_HOST_PORT}:5432"
    env_file:
      - ./ivy/.env # due to this, be careful when publishing any images! Don't publish any real secrets! TODO figure out how real devs manage this
