packages:
  - 'app/'
  - 'app-ugc/'
  - 'app-playwright/'
  - 'config/'
  - 'hub/'
  - 'hub-ugc/'
  - 'lrpc/'
  - 'shared/'
  - 'shared-dom/'
  - 'shared-edge/'
  - 'cwa/'
  - 'api-ugc/'
  - 'peer/'
  - 'example-plugins/*'
