/* eslint-disable */
// @ts-nocheck
// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  SimpleString = 1,
  Squared = 2,
  SquareOpen = 3,
  Dash = 4,
  Char = 5,
  RangeOpen = 6,
  RangeClose = 7,
  SquareClose = 8,
  Wildcard = 9,
  Wildcard1 = 10,
  Content = 11
