/* eslint-disable */
// @ts-nocheck
// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
import {queryHighlighting} from "./query.highlight.js"
const spec_SimpleString = {__proto__:null,tag:42, deck:50, template:52, OR:54}
export const parser = LRParser.deserialize({
  version: 14,
  states: "&lQVQPOOOnQPO'#CnO!fQPO'#CbO!mQPO'#CcO!rQPO'#CdO!wQPO'#CeO!|QPO'#CmOYQPO'#CmOOQO'#Cg'#CgQVQPOOOOQO,59Y,59YO#kQPO,58|O#pQPO,58}O#pQPO,59OO#pQPO,59POOQO'#Cf'#CfOOQO'#Ci'#CiO#xQPO'#CiO$PQPO,59XOOQO'#Cm'#CmO$PQPO,59XOOQO-E6e-E6eOOQO1G.h1G.hO$nQPO'#CsO#pQPO'#CsOOQO1G.i1G.iOOQO1G.j1G.jOOQO1G.k1G.kOOQO,59T,59TOOQO-E6g-E6gOOQO,59X,59XO%cQPO1G.sOOQO,59S,59SO&QQPO,59_OOQO-E6f-E6fPOQO1G.s1G.sP&uQPO'#ChO&zQPO'#CmOYQPO'#CmO'XQPO,59XO'XQPO,59XO'fQPO1G.sOYQPO'#Cm",
  stateData: "'v~O`OS~OQVORPOSPOcQOeROiSOjTO~OTYOQbXRbXSbX^bXcbXebXibXjbXkbXdbXhbX~OQzO~PYOf[O~Of]O~Of^O~Ok_OQaXRaXSaX^aXcaXeaXiaXjaX~OdfO~ORPOSPO~OQvO~PYOk_OQaaRaaSaa^aacaaeaaiaajaa~OhpOQgXRgXSgX^gXcgXegXigXjgXkgXdgX~Ok_OQaiRaiSai^aicaieaiiaijai~OhpOQgaRgaSga^gacgaegaigajgakgadga~OhpO~OQvOk_OdaX~PYOQvOk_Odaa~PYOQvOk_Odai~PYOQR~",
  goto: "$WhPPPPPPiiii!Q![!b!jPPP!|#^PPPP#}SUOXYcauwxyQdVQnvQuQRxzaaUbdouwxyQXOReXUh[]^RrhQbUWmbowyQodQwuRyxSWOXQZQW`uwxyRlaSUOXYcauwxyQdVUg[]^QnvQqhQuQRxzQi[Qj]Rk^",
  nodeNames: "⚠ Program Not SimpleString QuotedString Wildcard Group Tag Deck Template Or",
  maxTerm: 27,
  propSources: [queryHighlighting],
  skippedNodes: [0],
  repeatNodeCount: 3,
  tokenData: "(V~RrOX#]X^$m^p#]pq$mqr#]rs%bsx#]xy&`yz&ez{&j{|#]|}&o}!O&t!O![#]![!](Q!]#y#]#y#z$m#z$f#]$f$g$m$g#BY#]#BY#BZ$m#BZ$IS#]$IS$I_$m$I_$I|#]$I|$JO$m$JO$JT#]$JT$JU$m$JU$KV#]$KV$KW$m$KW&FU#]&FU&FV$m&FV;'S#];'S;=`$g<%lO#]~#baR~OX#]^p#]qr#]sx#]{|#]}![#]!]#y#]#z$f#]$g#BY#]#BZ$IS#]$I_$I|#]$JO$JT#]$JU$KV#]$KW&FU#]&FV;'S#];'S;=`$g<%lO#]~$jP;=`<%l#]~$rY`~X^$mpq$m#y#z$m$f$g$m#BY#BZ$m$IS$I_$m$I|$JO$m$JT$JU$m$KV$KW$m&FU&FV$m~%eVOr%brs%zs#O%b#O#P&P#P;'S%b;'S;=`&Y<%lO%b~&POS~~&SQrs%b#O#P%b~&]P;=`<%l%b~&eOc~~&jOd~~&oOT~~&tOh~~&{aQ~R~OX#]^p#]qr#]sx#]{|#]}![#]!]#y#]#z$f#]$g#BY#]#BZ$IS#]$I_$I|#]$JO$JT#]$JU$KV#]$KW&FU#]&FV;'S#];'S;=`$g<%lO#]~(VOf~",
  tokenizers: [0],
  topRules: {"Program":[0,1]},
  specialized: [{term: 3, get: (value: keyof typeof spec_SimpleString) => spec_SimpleString[value] || -1}],
  tokenPrec: 311
})
