/* eslint-disable */
// @ts-nocheck
// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  Program = 1,
  Not = 2,
  SimpleString = 3,
  QuotedString = 4,
  Wildcard = 5,
  Group = 6,
  Tag = 7,
  Deck = 8,
  Template = 9,
  Or = 10
