/* eslint-disable */
// @ts-nocheck
// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  Program = 1,
  Not = 2,
  Regex = 3,
  SimpleString = 4,
  QuotedString = 5,
  Wildcard = 6,
  Group = 7,
  LabeledGroup = 8,
  Deck = 9,
  Tag = 10,
  Template = 11,
  Or = 12,
  Labeled = 13
