/* eslint-disable */
// @ts-nocheck
// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
import {queryHighlighting} from "./query.highlight.js"
const spec_SimpleString = {__proto__:null,tag:44, deck:52, template:54, OR:56}
export const parser = LRParser.deserialize({
  version: 14,
  states: "&rQVQPOOOOQO'#Co'#CoOqQPO'#CoO!lQPO'#CcO!sQPO'#CdO!xQPO'#CeO!}QPO'#CfO#SQPO'#CnOYQPO'#CnOOQO'#Ch'#ChQVQPOOOOQO,59Z,59ZO#tQPO,58}O#yQPO,59OO#yQPO,59PO#yQPO,59QOOQO'#Cg'#CgOOQO'#Cj'#CjO$UQPO'#CjO$]QPO,59YOOQO'#Cn'#CnO$]QPO,59YOOQO-E6f-E6fOOQO1G.i1G.iO$}QPO'#CtO#yQPO'#CtOOQO1G.j1G.jOOQO1G.k1G.kOOQO1G.l1G.lOOQO,59U,59UOOQO-E6h-E6hOOQO,59Y,59YO%uQPO1G.tOOQO,59T,59TO&gQPO,59`OOQO-E6g-E6gPOQO1G.t1G.tP'_QPO'#CiO'dQPO'#CnOYQPO'#CnO'qQPO,59YO'qQPO,59YO(OQPO1G.tOYQPO'#Cn",
  stateData: "(`~OaOS~OQWORPOSQOTQOdROfSOjTOkUO~OUZOQcXRcXScXTcX_cXdcXfcXjcXkcXlcXecXicX~OQ{O~PYOg]O~Og^O~Og_O~Ol`OQbXRbXSbXTbX_bXdbXfbXjbXkbX~OegO~ORPOSQOTQO~OQwO~PYOl`OQbaRbaSbaTba_badbafbajbakba~OiqOQhXRhXShXThX_hXdhXfhXjhXkhXlhXehX~Ol`OQbiRbiSbiTbi_bidbifbijbikbi~OiqOQhaRhaShaTha_hadhafhajhakhalhaeha~OiqO~OQwOl`OebX~PYOQwOl`Oeba~PYOQwOl`Oebi~PYOQS~",
  goto: "$XiPPPPPPPjjjj!R!]!c!kPPP!}#_PPPP$OSVOYYdbvxyzQeWQowQvRRy{abVcepvxyzQYORfYUi]^_RsiQcVWncpxzQpeQxvRzySXOYQ[RWavxyzRmbSVOYYdbvxyzQeWUh]^_QowQriQvRRy{Qj]Qk^Rl_",
  nodeNames: "⚠ Program Not Regex SimpleString QuotedString Wildcard Group Tag Deck Template Or",
  maxTerm: 28,
  nodeProps: [
    ["isolate", 3,""]
  ],
  propSources: [queryHighlighting],
  skippedNodes: [0],
  repeatNodeCount: 3,
  tokenData: "+z~RuOX#fX^$|^p#fpq$|qr#frs%qsx#fxy&oyz&tz{&y{|#f|}'O}!O'T!O!P#f!P!Q(g!Q![#f![!]+u!]#O#f#P#y#f#y#z$|#z$f#f$f$g$|$g#BY#f#BY#BZ$|#BZ$IS#f$IS$I_$|$I_$I|#f$I|$JO$|$JO$JT#f$JT$JU$|$JU$KV#f$KV$KW$|$KW&FU#f&FU&FV$|&FV;'S#f;'S;=`$v<%lO#f~#kcS~OX#f^p#fqr#fsx#f{|#f}!P#f!Q![#f!]#O#f#P#y#f#z$f#f$g#BY#f#BZ$IS#f$I_$I|#f$JO$JT#f$JU$KV#f$KW&FU#f&FV;'S#f;'S;=`$v<%lO#f~$yP;=`<%l#f~%RYa~X^$|pq$|#y#z$|$f$g$|#BY#BZ$|$IS$I_$|$I|$JO$|$JT$JU$|$KV$KW$|&FU&FV$|~%tVOr%qrs&Zs#O%q#O#P&`#P;'S%q;'S;=`&i<%lO%q~&`OT~~&cQrs%q#O#P%q~&lP;=`<%l%q~&tOd~~&yOe~~'OOU~~'TOi~~'[cQ~S~OX#f^p#fqr#fsx#f{|#f}!P#f!Q![#f!]#O#f#P#y#f#z$f#f$g#BY#f#BZ$IS#f$I_$I|#f$JO$JT#f$JU$KV#f$KW&FU#f&FV;'S#f;'S;=`$v<%lO#f~(jWOY)SZ!P)S!Q!})S!}#O*a#O#P+`#P;'S)S;'S;=`+o<%lO)S~)VXOY)SZ!P)S!P!Q)r!Q!})S!}#O*a#O#P+`#P;'S)S;'S;=`+o<%lO)S~)wWR~#W#X)r#Z#[)r#]#^)r#a#b)r#g#h)r#i#j)r#j#k)r#m#n)r~*dVOY*aZ#O*a#O#P*y#P#Q)S#Q;'S*a;'S;=`+Y<%lO*a~*|SOY*aZ;'S*a;'S;=`+Y<%lO*a~+]P;=`<%l*a~+cSOY)SZ;'S)S;'S;=`+o<%lO)S~+rP;=`<%l)S~+zOg~",
  tokenizers: [0],
  topRules: {"Program":[0,1]},
  specialized: [{term: 4, get: (value: keyof typeof spec_SimpleString) => spec_SimpleString[value] || -1}],
  tokenPrec: 335
})
