/* eslint-disable */
// @ts-nocheck
// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
import {queryHighlighting} from "./query.highlight.js"
const spec_SimpleString = {__proto__:null,tag:38, deck:48, template:50, OR:52}
export const parser = LRParser.deserialize({
  version: 14,
  states: "&fQVQPOOOnQPO'#CaO!VQPO'#CbO![QPO'#CcO!aQPO'#CdO!fQPO'#ClO#TQPO'#ClOOQO'#Cf'#CfQVQPOOO#iQPO,58{O#nQPO,58|O#nQPO,58}O#nQPO,59OOOQO'#Ce'#CeOOQO'#Ch'#ChO#vQPO'#ChO$_QPO,59WOOQO'#Cl'#ClO$_QPO,59WOOQO-E6d-E6dOOQO1G.g1G.gOOQO'#Cr'#CrO$|QPO'#CqO#nQPO'#CqOOQO1G.h1G.hOOQO1G.i1G.iOOQO1G.j1G.jOOQO,59S,59SOOQO-E6f-E6fOOQO,59W,59WO%qQPO1G.rOOQO,59R,59RO&`QPO,59]OOQO-E6e-E6ePOQO1G.r1G.rP'TQPO'#CgO'YQPO'#ClO'dQPO'#ClO'xQPO,59WO'xQPO,59WO(SQPO1G.rO(^QPO'#Cl",
  stateData: "(u~O_OS~OQUORTOSTOaPOcQOhROiSO~OQyORtOStOaPOcQOhROiSO~OdYO~OdZO~Od[O~Oj]OQ`XR`XS`X]`Xa`Xc`Xh`Xi`X~ORbOSbOaPOcQOhROiSO~ObdO~OReOSeO~OQuORaOSaOaPOcQOhROiSO~Oj]OQ`aR`aS`a]`aa`ac`ah`ai`a~OgoOQeXReXSeX]eXaeXceXheXieXjeXbeX~Oj]OQ`iR`iS`i]`ia`ic`ih`ii`i~OgoOQeaReaSea]eaaeaceaheaieajeabea~OgoO~Oj]Ob`X~P#vORmOSmOaPOcQOhROiSO~Oj]Ob`a~P#vOj]Ob`i~P#vORwOSwOaPOcQOhROiSO~OQR~",
  goto: "#ngPPPPPhhhh!P!Z!a!iPPP!{PPPP#]#fSTOWYa_tvwxQbUQmuQtPRwya_T`bntvwxQWORcWUgYZ[RqgQ`TWl`nvxQnbQvtRxwSVOWQXPW^tvwxRk_QhYQiZRj[UfYZ[Rpg",
  nodeNames: "⚠ Program Not SimpleString QuotedString Group Tag Deck Template Or",
  maxTerm: 26,
  propSources: [queryHighlighting],
  skippedNodes: [0],
  repeatNodeCount: 3,
  tokenData: "'}~RqOX#YX^$j^p#Ypq$jqr#Yrs%_sx#Yxy&]yz&bz|#Y|}&g}!O&l!O![#Y![!]'x!]#y#Y#y#z$j#z$f#Y$f$g$j$g#BY#Y#BY#BZ$j#BZ$IS#Y$IS$I_$j$I_$I|#Y$I|$JO$j$JO$JT#Y$JT$JU$j$JU$KV#Y$KV$KW$j$KW&FU#Y&FU&FV$j&FV;'S#Y;'S;=`$d<%lO#Y~#_aR~OX#Y^p#Yqr#Ysx#Yz|#Y}![#Y!]#y#Y#z$f#Y$g#BY#Y#BZ$IS#Y$I_$I|#Y$JO$JT#Y$JU$KV#Y$KW&FU#Y&FV;'S#Y;'S;=`$d<%lO#Y~$gP;=`<%l#Y~$oY_~X^$jpq$j#y#z$j$f$g$j#BY#BZ$j$IS$I_$j$I|$JO$j$JT$JU$j$KV$KW$j&FU&FV$j~%bVOr%_rs%ws#O%_#O#P%|#P;'S%_;'S;=`&V<%lO%_~%|OS~~&PQrs%_#O#P%_~&YP;=`<%l%_~&bOa~~&gOb~~&lOg~~&saQ~R~OX#Y^p#Yqr#Ysx#Yz|#Y}![#Y!]#y#Y#z$f#Y$g#BY#Y#BZ$IS#Y$I_$I|#Y$JO$JT#Y$JU$KV#Y$KW&FU#Y&FV;'S#Y;'S;=`$d<%lO#Y~'}Od~",
  tokenizers: [0],
  topRules: {"Program":[0,1]},
  specialized: [{term: 3, get: (value: keyof typeof spec_SimpleString) => spec_SimpleString[value] || -1}],
  tokenPrec: 356
})
