/* eslint-disable */
// @ts-nocheck
// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
import {startTag, elementContext} from "./template.tokens.ts"
import {xmlHighlighting} from "./template.highlight.ts"
export const parser = LRParser.deserialize({
  version: 14,
  states: "$tOQOROOOcOSO'#ClOnORO'#CeOOOP'#Ce'#CeOxOSO'#CoOOOP'#Cs'#CsOOOP'#Cp'#CpQQOROOO}OSO,59RO!SOSO,59WOOOO'#Cq'#CqO![OSO,59WO!aOSO'#CkOOOP,59P,59PO!fORO,59PO!pOSO,59ZOOOP-E6n-E6nO!uOSO1G.mOOOO,59Y,59YOOOP1G.r1G.rO!zOSO1G.rOOOO-E6o-E6oO#SOSO,59VOOOP1G.k1G.kOOOP1G.u1G.uOOOP7+$X7+$XOOOP7+$^7+$^P!VOSO'#CnOOOP1G.q1G.q",
  stateData: "#X~OPPOSSOTTOVTOWTO~O[WO]WO^XO~OQ[OR]O~PQO^_O~O^aO~OYcOabO~O^dO~O^fO~OQ[ORgO~PQOYhO~OYiO~OYjOabO~OYlO~O",
  goto: "!mhPPPPPPPPPiPoPPPu{P!Ri!V!aP!gXTOQV^XQOQV^Q]QRg^XROQV^TYPZQVOQ^QT`V^QZPReZXUOQV^",
  nodeNames: "⚠ StartTag StartCloseTag MissingCloseTag StartCloseTag StartCloseTag Document Text Text Element EndTag OpenTag If Unless TagName CloseTag SelfClosingTag TransformerDelimiter Transformer MismatchedCloseTag",
  maxTerm: 23,
  context: elementContext,
  nodeProps: [
    ["closedBy", 1,"EndTag",11,"CloseTag MissingCloseTag"],
    ["openedBy", 10,"StartTag StartCloseTag",15,"OpenTag"],
    ["isolate", -4,11,15,16,19,""]
  ],
  propSources: [xmlHighlighting],
  skippedNodes: [0],
  repeatNodeCount: 2,
  tokenData: "%{~RcOp!^pq!uqs!^st#ot!Q!^!Q![!u![!]$S!]!c!^!c!}!u!}#Q!^#Q#R$g#R#T!^#T#o!u#o#p$z#p#q!^#q#r%P#r;'S!^;'S;=`!o<%lO!^P!cSVPO#o!^#p;'S!^;'S;=`!o<%lO!^P!rP;=`<%l!^R!|Z^QVPOp!^pq!uq!Q!^!Q![!u![!c!^!c!}!u!}#T!^#T#o!u#p;'S!^;'S;=`!o<%lO!^R#vS[QVPO#o!^#p;'S!^;'S;=`!o<%lO!^R$ZSVPaQO#o!^#p;'S!^;'S;=`!o<%lO!^R$nSVP]QO#o!^#p;'S!^;'S;=`!o<%lO!^~%POW~R%UUVPO#o!^#p#q!^#q#r%h#r;'S!^;'S;=`!o<%lO!^R%oSYQVPO#o!^#p;'S!^;'S;=`!o<%lO!^",
  tokenizers: [startTag, 0, 1],
  topRules: {"Document":[0,6]},
  tokenPrec: 0
})
