service: trpc-hello-world
frameworkVersion: "3"

custom:
  tableName: "ivy-table-${sls:stage}"
  dynamodb:
    start:
      migrate: true
    stages:
      - dev

provider:
  name: aws
  runtime: nodejs14.x
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            # https://docs.aws.amazon.com/service-authorization/latest/reference/list_amazondynamodb.html
            - dynamodb:Query
            - dynamodb:GetItem
            - dynamodb:PutItem
          Resource:
            - Fn::GetAtt: [IvyTable, Arn]
  environment:
    IVY_TABLE: ${self:custom.tableName}

functions:
  http-api:
    handler: .build/src/lambdaHandler.handler
    events:
      - httpApi: "*"
  rest-api:
    handler: .build/src/lambdaHandler.handler
    events:
      - http:
          path: /{proxy+}
          method: any

resources:
  Resources:
    IvyTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.tableName}
        BillingMode: PAY_PER_REQUEST
        KeySchema:
          - AttributeName: PK
            KeyType: HASH
          - AttributeName: SK
            KeyType: RANGE
        AttributeDefinitions:
          - AttributeName: PK
            AttributeType: S
          - AttributeName: SK
            AttributeType: S

plugins:
  - serverless-plugin-typescript
  - serverless-dynamodb-local
  - serverless-offline
