service: trpc-hello-world
frameworkVersion: "3"

custom:
  tableName: "ivy-table-${sls:stage}"
  dynamodb:
    start:
      migrate: true
    stages:
      - dev

provider:
  name: aws
  runtime: nodejs14.x

functions:
  http-api:
    handler: .build/src/lambdaHandler.handler
    events:
      - httpApi: "*"
  rest-api:
    handler: .build/src/lambdaHandler.handler
    events:
      - http:
          path: /{proxy+}
          method: any

plugins:
  - serverless-plugin-typescript
  - serverless-offline
