export cloudflareAccountId=
export developmentPlanetscaleDbUrl=
export productionPlanetscaleDbUrl=
export developmentMediaTokenSecret=you+should+replace+this+with+a+real+base64+=
export productionMediaTokenSecret=you+should+replace+this+with+a+real+base64+=
export developmentHubSessionSecret=secret/you+can+run+the+command+which+kinda+=
export productionHubSessionSecret=secret/you+can+run+the+command+which+kinda+=
export developmentJwsSecret=looks+like+openssl+rand+base64+32+comma+but=
export productionJwsSecret=looks+like+openssl+rand+base64+32+comma+but=
export developmentCsrfSecret=with+spaces+and+hyphens+and+stuff+ZZZZZZZZZ=
export productionCsrfSecret=with+spaces+and+hyphens+and+stuff+ZZZZZZZZZ=
export developmentAppOrigin=https://app.pentive.local:3013
export productionAppOrigin=https://app.pentive.com
export developmentHubOrigin=https://pentive.local:3014
export productionHubOrigin=https://pentive.com
export VITE_DEVELOPMENT_HUB_DOMAIN=pentive.local
export VITE_PRODUCTION_HUB_DOMAIN=hub.yourusernamehere.workers.dev
export VITE_DEVELOPMENT_CWA_URL=https://cwa.pentive.local:3017/
export VITE_PRODUCTION_CWA_URL=https://cwa.yourusernamehere.workers.dev/
export VITE_DEVELOPMENT_APP_ORIGIN=https://app.pentive.local:3013
export VITE_PRODUCTION_APP_ORIGIN=https://app.yourusernamehere.workers.dev
export VITE_DEVELOPMENT_HUB_UGC_ORIGIN=https://hub-user-generated-content.pentive.local:3016
export VITE_PRODUCTION_HUB_UGC_ORIGIN=https://hub-user-generated-content.yourusernamehere.workers.dev
export VITE_DEVELOPMENT_APP_UGC_ORIGIN=https://app-user-generated-content.pentive.local:3015
export VITE_PRODUCTION_APP_UGC_ORIGIN=https://app-user-generated-content.yourusernamehere.workers.dev
export VITE_DEVELOPMENT_PEER_HOST=peer.pentive.local
export VITE_DEVELOPMENT_PEER_PORT="3018"
export VITE_PRODUCTION_PEER_HOST="0.peerjs.com"
export VITE_PRODUCTION_PEER_PORT="443"
