name = "mediarouter"
main = "src/index.ts"
compatibility_date = "2022-12-14"

account_id = "$cloudflareAccountId"

[[r2_buckets]]
binding = 'mediaBucket'
bucket_name = 'media'
preview_bucket_name = 'media-dev'

# https://developers.cloudflare.com/workers/wrangler/configuration/#environmental-variables
# https://developers.cloudflare.com/workers/platform/environment-variables/#adding-secrets-via-wrangler

# The necessary secrets are:
# - jwsPublicKey
# - jwsPrivateKey
# Run `echo <VALUE> | wrangler secret put <NAME>` for each of these
