name = "api-ugc"
main = "src/index.ts"
compatibility_date = "2024-08-12"

account_id = "$cloudflareAccountId"

[[r2_buckets]]
binding = 'mediaBucket'
bucket_name = 'media'
preview_bucket_name = 'media-dev'

[dev]
port = 3019
local_protocol = "https"

