name = "cwa"
main = "src/index.ts"
compatibility_date = "2024-08-12"

account_id = "$cloudflareAccountId"

[dev]
port = 3017
local_protocol = "https"

[define]
HUB_ORIGIN = "'$developmentHubOrigin'"
APP_ORIGIN = "'$developmentAppOrigin'"

[[r2_buckets]]
binding = 'mediaBucket'
bucket_name = 'media'
preview_bucket_name = 'media-dev'


# =====================================
# 🚨 PRODUCTION CONFIG 🚨
# =====================================

[env.production.define]
HUB_ORIGIN = "'$productionHubOrigin'"
APP_ORIGIN = "'$productionAppOrigin'"

[[env.production.r2_buckets]]
binding = 'mediaBucket'
bucket_name = 'media'
