/* eslint-disable */
// @ts-nocheck
// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
const spec_SimpleString = {__proto__:null,tag:32, deck:36}
export const parser = LRParser.deserialize({
  version: 14,
  states: "#SOVQPOOOnQPO'#CbOsQPO'#CcOOQO'#Ci'#CiOxQPO'#CiOOQO'#Ce'#CeQVQPOOOVQPO'#CaO!ZQPO,58|O!cQPO,58}OOQO,59T,59TOOQO-E6c-E6cO!kQPO,58{OOQO1G.h1G.hOOQO1G.i1G.iOOQO1G.g1G.g",
  stateData: "!w~O[OS~OQSORROSROWTO^VO`PObQO~OaWO~OaXO~ORYOSYO^VO`PObQO~OR]OS]O~OR^OS^O~O__O~PVOWQRQ~",
  goto: "x^PPPPP___PhPPPrWROUV[RYSQUOSZU[R[VXTOUV[",
  nodeNames: "⚠ Program Not SimpleString QuotedString ParenthesizedExpression Tag Deck Or",
  maxTerm: 18,
  skippedNodes: [0],
  repeatNodeCount: 1,
  tokenData: "*]~RrOX#]X^$j^p#]pq$jqr#]rs%_sx#]xy&]yz&bz}#]}!O&g!O![#]![!]'p!]!q#]!q!r'u!r#y#]#y#z$j#z$f#]$f$g$j$g#BY#]#BY#BZ$j#BZ$IS#]$IS$I_$j$I_$I|#]$I|$JO$j$JO$JT#]$JT$JU$j$JU$KV#]$KV$KW$j$KW&FU#]&FU&FV$j&FV;'S#];'S;=`$d<%lO#]~#b`R~OX#]^p#]qr#]sx#]z![#]!]#y#]#z$f#]$g#BY#]#BZ$IS#]$I_$I|#]$JO$JT#]$JU$KV#]$KW&FU#]&FV;'S#];'S;=`$d<%lO#]~$gP;=`<%l#]~$oY[~X^$jpq$j#y#z$j$f$g$j#BY#BZ$j$IS$I_$j$I|$JO$j$JT$JU$j$KV$KW$j&FU&FV$j~%bVOr%_rs%ws#O%_#O#P%|#P;'S%_;'S;=`&V<%lO%_~%|OS~~&PQrs%_#O#P%_~&YP;=`<%l%_~&bO^~~&gO_~~&n`Q~R~OX#]^p#]qr#]sx#]z![#]!]#y#]#z$f#]$g#BY#]#BZ$IS#]$I_$I|#]$JO$JT#]$JU$KV#]$KW&FU#]&FV;'S#];'S;=`$d<%lO#]~'uOa~~'zbR~OX#]^p#]qr#]sx#]z![#]!]!t#]!t!u)S!u#y#]#z$f#]$g#BY#]#BZ$IS#]$I_$I|#]$JO$JT#]$JU$KV#]$KW&FU#]&FV;'S#];'S;=`$d<%lO#]~)Z`W~R~OX#]^p#]qr#]sx#]z![#]!]#y#]#z$f#]$g#BY#]#BZ$IS#]$I_$I|#]$JO$JT#]$JU$KV#]$KW&FU#]&FV;'S#];'S;=`$d<%lO#]",
  tokenizers: [0],
  topRules: {"Program":[0,1]},
  specialized: [{term: 3, get: (value: any) => spec_SimpleString[value] || -1}],
  tokenPrec: 80
})
