/* eslint-disable */
// @ts-nocheck
// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  Program = 1,
  Not = 2,
  SimpleString = 3,
  QuotedString = 4,
  Group = 5,
  Tag = 6,
  Deck = 7,
  Template = 8,
  Or = 9
