/* eslint-disable */
// @ts-nocheck
// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
const spec_SimpleString = {__proto__:null,tag:36, deck:40, template:42, OR:44}
export const parser = LRParser.deserialize({
  version: 14,
  states: "%jQVQPOOOnQPO'#CaO!VQPO'#CbO![QPO'#CcO!aQPO'#CdO!fQPO'#CkO#TQPO'#CkOOQO'#Cf'#CfQVQPOOO#iQPO,58{O#nQPO,58|O#vQPO,58}O$OQPO,59OOOQO'#Ce'#CeOOQO'#Cg'#CgO$WQPO'#CgO$oQPO,59VOOQO'#Ck'#CkO$oQPO,59VOOQO-E6d-E6dOOQO1G.g1G.gOOQO1G.h1G.hOOQO1G.i1G.iOOQO1G.j1G.jOOQO,59R,59ROOQO-E6e-E6eOOQO,59V,59VO%^QPO1G.qPOQO1G.q1G.qO%{QPO'#CkO&VQPO'#CkO&kQPO,59VO&kQPO,59VO&uQPO1G.qO'PQPO'#Ck",
  stateData: "'h~O^OS~OQUORTOSTO`PObQOdROeSO~OQrORmOSmO`PObQOdROeSO~OcYO~OcZO~Oc[O~Of]OQ_XR_XS_X[_X`_Xb_Xd_Xe_X~ORbOSbO`PObQOdROeSO~OadO~OReOSeO~ORfOSfO~ORgOSgO~OQnORaOSaO`PObQOdROeSO~Of]OQ_aR_aS_a[_a`_ab_ad_ae_a~Of]OQ_iR_iS_i[_i`_ib_id_ie_i~Of]Oa_X~P$WORjOSjO`PObQOdROeSO~Of]Oa_a~P$WOf]Oa_i~P$WORpOSpO`PObQOdROeSO~OQR~",
  goto: "!|`PPPPPaaaax!S!YPPP!lSTOWYa_mopqQbUQjnQmPRpra_T`bkmopqQWORcWQ`TWi`koqQkbQomRqpSVOWQXPW^mopqRh_",
  nodeNames: "⚠ Program Not SimpleString QuotedString Group Tag Deck Template Or",
  maxTerm: 22,
  skippedNodes: [0],
  repeatNodeCount: 2,
  tokenData: "'o~RpOX#VX^$d^p#Vpq$dqr#Vrs%Xsx#Vxy&Vyz&[z}#V}!O&a!O![#V![!]'j!]#y#V#y#z$d#z$f#V$f$g$d$g#BY#V#BY#BZ$d#BZ$IS#V$IS$I_$d$I_$I|#V$I|$JO$d$JO$JT#V$JT$JU$d$JU$KV#V$KV$KW$d$KW&FU#V&FU&FV$d&FV;'S#V;'S;=`$^<%lO#V~#[`R~OX#V^p#Vqr#Vsx#Vz![#V!]#y#V#z$f#V$g#BY#V#BZ$IS#V$I_$I|#V$JO$JT#V$JU$KV#V$KW&FU#V&FV;'S#V;'S;=`$^<%lO#V~$aP;=`<%l#V~$iY^~X^$dpq$d#y#z$d$f$g$d#BY#BZ$d$IS$I_$d$I|$JO$d$JT$JU$d$KV$KW$d&FU&FV$d~%[VOr%Xrs%qs#O%X#O#P%v#P;'S%X;'S;=`&P<%lO%X~%vOS~~%yQrs%X#O#P%X~&SP;=`<%l%X~&[O`~~&aOa~~&h`Q~R~OX#V^p#Vqr#Vsx#Vz![#V!]#y#V#z$f#V$g#BY#V#BZ$IS#V$I_$I|#V$JO$JT#V$JU$KV#V$KW&FU#V&FV;'S#V;'S;=`$^<%lO#V~'oOc~",
  tokenizers: [0],
  topRules: {"Program":[0,1]},
  specialized: [{term: 3, get: (value: any) => spec_SimpleString[value] || -1}],
  tokenPrec: 297
})
