/* eslint-disable */
// @ts-nocheck
// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
const spec_SimpleString = {__proto__:null,tag:34, deck:38, OR:40}
export const parser = LRParser.deserialize({
  version: 14,
  states: "%WQVQPOOOkQPO'#CaO!PQPO'#CbO!UQPO'#CcO!ZQPO'#CjO!uQPO'#CjOOQO'#Ce'#CeQVQPOOO#WQPO,58{O#]QPO,58|O#eQPO,58}OOQO'#Cd'#CdOOQO'#Cf'#CfO#mQPO'#CfO$RQPO,59UOOQO'#Cj'#CjO$RQPO,59UOOQO-E6c-E6cOOQO1G.g1G.gOOQO1G.h1G.hOOQO1G.i1G.iOOQO,59Q,59QOOQO-E6d-E6dOOQO,59U,59UO$mQPO1G.pPOQO1G.p1G.pO%XQPO'#CjO%cQPO'#CjO%tQPO,59UO%tQPO,59UO&OQPO1G.pO&YQPO'#Cj",
  stateData: "&n~O]OS~OQTORSOSSO_POaQOcRO~OQoORjOSjO_POaQOcRO~ObXO~ObYO~OdZOQ^XR^XS^XZ^X_^Xa^Xc^X~OR`OS`O_POaQOcRO~O`bO~ORcOScO~ORdOSdO~OQkOR_OS_O_POaQOcRO~OdZOQ^aR^aS^aZ^a_^aa^ac^a~OdZOQ^iR^iS^iZ^i_^ia^ic^i~OdZO`^X~P#mORgOSgO_POaQOcRO~OdZO`^a~P#mOdZO`^i~P#mORmOSmO_POaQOcRO~OQR~",
  goto: "!{_PPPPP```w!R!XPPP!kSSOVY_]jlmnQ`TQgkQjPRmoa]S^`hjlmnQVORaVQ^SWf^hlnQh`QljRnmSUOVQWPW[jlmnRe]",
  nodeNames: "⚠ Program Not SimpleString QuotedString ParenthesizedExpression Tag Deck Or",
  maxTerm: 20,
  skippedNodes: [0],
  repeatNodeCount: 2,
  tokenData: "'o~RpOX#VX^$d^p#Vpq$dqr#Vrs%Xsx#Vxy&Vyz&[z}#V}!O&a!O![#V![!]'j!]#y#V#y#z$d#z$f#V$f$g$d$g#BY#V#BY#BZ$d#BZ$IS#V$IS$I_$d$I_$I|#V$I|$JO$d$JO$JT#V$JT$JU$d$JU$KV#V$KV$KW$d$KW&FU#V&FU&FV$d&FV;'S#V;'S;=`$^<%lO#V~#[`R~OX#V^p#Vqr#Vsx#Vz![#V!]#y#V#z$f#V$g#BY#V#BZ$IS#V$I_$I|#V$JO$JT#V$JU$KV#V$KW&FU#V&FV;'S#V;'S;=`$^<%lO#V~$aP;=`<%l#V~$iY]~X^$dpq$d#y#z$d$f$g$d#BY#BZ$d$IS$I_$d$I|$JO$d$JT$JU$d$KV$KW$d&FU&FV$d~%[VOr%Xrs%qs#O%X#O#P%v#P;'S%X;'S;=`&P<%lO%X~%vOS~~%yQrs%X#O#P%X~&SP;=`<%l%X~&[O_~~&aO`~~&h`Q~R~OX#V^p#Vqr#Vsx#Vz![#V!]#y#V#z$f#V$g#BY#V#BZ$IS#V$I_$I|#V$JO$JT#V$JU$KV#V$KW&FU#V&FV;'S#V;'S;=`$^<%lO#V~'oOb~",
  tokenizers: [0],
  topRules: {"Program":[0,1]},
  specialized: [{term: 3, get: (value: any) => spec_SimpleString[value] || -1}],
  tokenPrec: 257
})
