name = "miniflare-typescript-esbuild-jest"
main = "dist/index.mjs"
compatibility_date = "2024-08-12"
compatibility_flags = []

[durable_objects]
bindings = [{ name = "COUNTER", class_name = "Counter" }]

[[migrations]]
tag = "v1"
new_classes = ["Counter"]

[build]
command = "node build.js"

[miniflare]
kv_persist = true
cache_persist = true
durable_objects_persist = true
