name: CI/CD

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'

jobs:
  check_and_deploy:
    name: check and deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v2

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          cache: pnpm
          node-version-file: '.nvmrc'

      - name: pnpm install
        run: pnpm install

      - name: tsc-build
        run: pnpm tsc-build

      - name: eslint + test
        run: pnpm eslint+test

      - name: envsubst
        env:
          cloudflareAccountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          productionPeerSyncPublicKey: ${{ secrets.PEER_SYNC_PUBLIC_KEY }}
          VITE_PRODUCTION_AG_GRID_LICENSE: ${{ secrets.AG_GRID_LICENSE }}
          VITE_PRODUCTION_HUB_DOMAIN: pentive.com
          VITE_PRODUCTION_HUB_ORIGIN: https://pentive.com
          VITE_PRODUCTION_CWA_URL: https://cwa.pentive.com/
          VITE_PRODUCTION_AUGC_URL: https://api-ugc.alexerrant.workers.dev/
          VITE_PRODUCTION_APP_ORIGIN: https://app.pentive.com
          VITE_PRODUCTION_HUB_UGC_ORIGIN: https://hub-ugc.pages.dev
          VITE_PRODUCTION_APP_UGC_ORIGIN: https://app-ugc.pages.dev
          VITE_PRODUCTION_PEER_HOST: 0.peerjs.com
          VITE_PRODUCTION_PEER_PORT: 443
        run: |
          envsubst <       ./cwa/example.wrangler.toml >     ./cwa/wrangler.toml
          envsubst <   ./api-ugc/example.wrangler.toml > ./api-ugc/wrangler.toml
          envsubst <       ./hub/example.wrangler.toml >     ./hub/wrangler.toml
          envsubst <     ./hub/.example.env.production >     ./hub/.env.production
          envsubst < ./hub-ugc/.example.env.production > ./hub-ugc/.env.production
          envsubst <     ./app/.example.env.production >     ./app/.env.production

      - name: build
        run: pnpm build

      - name: deploy
        run: pnpm run deploy
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
